services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: mediaquest_db
      POSTGRES_USER: mediaquest_user
      POSTGRES_PASSWORD: mediaquest_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_DATABASE: mediaquest_content_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
